### PR TITLE
[config] Enable AXP15060 regulator

### PR DESCRIPTION
**Pull request by Manorhos**
Needed on Star64 for CPUFreq support. Without it, the CPU was stuck at 750 MHz, now reclocking works and it can run at 1.5 GHz.

Thanks for working on support for this SBC, btw! I built the kernel with amdgpu and am running DietPi with an AMD Radeon HD 7870, runs quite well!

### CODE REVIEW

**Comment by MichaIng** [comment]
Ah many thanks, I was already wondering about that and thought that I need to add some more device tree updates from the VisionFive 2 6.1 branch (there were some CPU-related ones).

I `CONFIG_REGULATOR_AXP20X` then probably not required, but only for the VisionFive 2?

**Comment by Manorhos** [comment]
Now that you say it, it might be more of a device tree issue after all...

AXP15060 support has been added to the axp20x driver (and upstreamed already), so it seems they switched over to that driver: https://github.com/MichaIng/linux/commit/e4c4547fb2c4f181b149816eb3607f5be94b5fad

Maybe some device tree modification is needed for the new driver to recognize the regulator?

**Comment by MichaIng** [comment]
Probably this one: https://github.com/MichaIng/linux/commit/3371da8

**Comment by MichaIng** [comment]
New build running: https://github.com/MichaIng/linux/actions/runs/7504743283/job/20432498133
Also with a rebase onto Linux v6.1.72 and I added some WiFi/BT firmware and a StarFive DRI library which the driver is expecting. Due to the rebase, this PR/commit needs to be rebased as well, but probably it won't be required anymore.

**Comment by MichaIng** [comment]
Jep, that was it 🙂:
```console
2024-01-12 17:43:09 root@Star64:~# cpu

 ─────────────────────────────────────────────────────
 DietPi CPU Info
 Use dietpi-config to change CPU / performance options
 ─────────────────────────────────────────────────────
 Architecture |     riscv64
 Temperature  |     48 °C / 118 °F : Optimal temperature
 Governor     |     schedutil

                 Current Freq    Min Freq   Max Freq
 CPU0         |      750 MHz      312 MHz    1500 MHz
 CPU1         |      750 MHz      312 MHz    1500 MHz
 CPU2         |      750 MHz      312 MHz    1500 MHz
 CPU3         |      750 MHz      312 MHz    1500 MHz

[ INFO ] DietPi-CPU_info | The current CPU frequency may be affected by processing this script itself.

2024-01-12 17:43:58 root@Star64:~# ls -l /sys/devices/system/cpu/cpu0/cpufreq/
total 0
-r--r--r-- 1 root root 4096 Jan 12 17:44 affected_cpus
-r-------- 1 root root 4096 Jan 12 17:44 cpuinfo_cur_freq
-r--r--r-- 1 root root 4096 Jan 12 17:44 cpuinfo_max_freq
-r--r--r-- 1 root root 4096 Jan 12 17:44 cpuinfo_min_freq
-r--r--r-- 1 root root 4096 Jan 12 17:44 cpuinfo_transition_latency
-r--r--r-- 1 root root 4096 Jan 12 17:44 related_cpus
-r--r--r-- 1 root root 4096 Jan 12 17:42 scaling_available_frequencies
-r--r--r-- 1 root root 4096 Jan 12 17:42 scaling_available_governors
-r--r--r-- 1 root root 4096 Jan 12 17:43 scaling_cur_freq
-r--r--r-- 1 root root 4096 Jan 12 17:44 scaling_driver
-rw-r--r-- 1 root root 4096 Jan 12 17:42 scaling_governor
-rw-r--r-- 1 root root 4096 Jan 12 17:42 scaling_max_freq
-rw-r--r-- 1 root root 4096 Jan 12 17:42 scaling_min_freq
-rw-r--r-- 1 root root 4096 Jan 12 17:44 scaling_setspeed
drwxr-xr-x 2 root root    0 Jan 12 17:44 stats
```
I updated the packages on our server already: https://dietpi.com/downloads/binaries/

I'll hence close this PR, many thanks for bringing this up!

**Comment by Manorhos** [comment]
Yeah, awesome, just recompiled and it works without the extra driver 🥳

**Pull request closed without merging**
